### ISSUE TITLE
Improve dask example notebooks (incl. Dyamond2)

### ISSUE THREAD

**Issue by tcmetzger** [earth-system-radiation/pyRTE-RRTMGP#100]
Improve the dask-based examples as discussed here: 

https://github.com/earth-system-radiation/pyRTE-RRTMGP/pull/98#discussion_r1967882617

**Comment by tcmetzger** [comment]
@brendancol Since we are using things like black and isort in our pre-commit configuration for the main package, we could also add some notebook-specific linting to our pre-commit config.

Something like this:


```yml
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
    -   id: nbqa-black
        files: \.ipynb$
    -   id: nbqa-flake8
        files: \.ipynb$
    -   id: nbqa-isort
        files: \.ipynb$

-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    -   id: nbstripout

```
This might need to be adapted, I haven't tested this!
